# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ztzka\eric6\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setFixedSize(1000,600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Project/Python/JavInfo/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 980, 580))
        self.tabWidget.setObjectName("tabWidget")
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.label_10 = QtWidgets.QLabel(self.search)
        self.label_10.setGeometry(QtCore.QRect(49, 449, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.search)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(719, 289, 251, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.Descriotion = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.Descriotion.setObjectName("Descriotion")
        self.verticalLayout.addWidget(self.Descriotion)
        self.Cover = QtWidgets.QGraphicsView(self.search)
        self.Cover.setGeometry(QtCore.QRect(49, 39, 630, 410))
        self.Cover.setObjectName("Cover")
        self.gridLayoutWidget = QtWidgets.QWidget(self.search)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(720, 110, 251, 172))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.search)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(719, 39, 251, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.selectSite = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.selectSite.setObjectName("selectSite")
        self.selectSite.addItem("")
        self.selectSite.addItem("")
        self.selectSite.addItem("")
        self.selectSite.addItem("")
        self.selectSite.addItem("")
        self.selectSite.addItem("")
        self.selectSite.addItem("")
        self.horizontalLayout_2.addWidget(self.selectSite)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.search)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(719, 69, 251, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.inputID = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.inputID.setObjectName("inputID")
        self.horizontalLayout.addWidget(self.inputID)
        self.Search = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Search.setEnabled(True)
        self.Search.setObjectName("Search")
        self.horizontalLayout.addWidget(self.Search)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.search)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(48, 468, 921, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.downloadPATH = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.downloadPATH.setObjectName("downloadPATH")
        self.gridLayout_2.addWidget(self.downloadPATH, 1, 1, 1, 1)
        self.downloadURL = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.downloadURL.setObjectName("downloadURL")
        self.gridLayout_2.addWidget(self.downloadURL, 0, 1, 1, 1)
        self.downloadButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout_2.addWidget(self.downloadButton, 1, 2, 1, 1)
        self.statu = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.statu.setToolTip("")
        self.statu.setAlignment(QtCore.Qt.AlignCenter)
        self.statu.setObjectName("statu")
        self.gridLayout_2.addWidget(self.statu, 0, 2, 1, 1)
        self.releaseDate = QtWidgets.QLineEdit(self.search)
        self.releaseDate.setGeometry(QtCore.QRect(720, 260, 121, 20))
        self.releaseDate.setObjectName("releaseDate")
        self.label_5 = QtWidgets.QLabel(self.search)
        self.label_5.setGeometry(QtCore.QRect(847, 242, 122, 12))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.search)
        self.label_4.setGeometry(QtCore.QRect(720, 242, 121, 12))
        self.label_4.setObjectName("label_4")
        self.Duration = QtWidgets.QLineEdit(self.search)
        self.Duration.setGeometry(QtCore.QRect(847, 260, 122, 20))
        self.Duration.setObjectName("Duration")
        self.label_6 = QtWidgets.QLabel(self.search)
        self.label_6.setGeometry(QtCore.QRect(720, 198, 249, 12))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.search)
        self.label_2.setGeometry(QtCore.QRect(720, 110, 249, 12))
        self.label_2.setObjectName("label_2")
        self.Tags = QtWidgets.QLineEdit(self.search)
        self.Tags.setGeometry(QtCore.QRect(720, 216, 249, 20))
        self.Tags.setObjectName("Tags")
        self.label_3 = QtWidgets.QLabel(self.search)
        self.label_3.setGeometry(QtCore.QRect(720, 154, 249, 12))
        self.label_3.setObjectName("label_3")
        self.Actor = QtWidgets.QLineEdit(self.search)
        self.Actor.setGeometry(QtCore.QRect(720, 172, 249, 20))
        self.Actor.setObjectName("Actor")
        self.Title = QtWidgets.QLineEdit(self.search)
        self.Title.setGeometry(QtCore.QRect(720, 128, 249, 20))
        self.Title.setObjectName("Title")
        self.tabWidget.addTab(self.search, "")
        self.download = QtWidgets.QWidget()
        self.download.setObjectName("download")
        self.output = QtWidgets.QTextBrowser(self.download)
        self.output.setGeometry(QtCore.QRect(50, 50, 850, 460))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        self.output.setObjectName("output")
        self.tabWidget.addTab(self.download, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JavInfo"))
        self.label_10.setText(_translate("MainWindow", "下载"))
        self.label_7.setText(_translate("MainWindow", "简介"))
        self.label_8.setText(_translate("MainWindow", "选择站点"))
        self.selectSite.setItemText(0, _translate("MainWindow", "1pondo"))
        self.selectSite.setItemText(1, _translate("MainWindow", "Caribbeancom"))
        self.selectSite.setItemText(2, _translate("MainWindow", "Caribbeancompr"))
        self.selectSite.setItemText(3, _translate("MainWindow", "Heyzo"))
        self.selectSite.setItemText(4, _translate("MainWindow", "Ken8tengoku"))
        self.selectSite.setItemText(5, _translate("MainWindow", "R18.com"))
        self.selectSite.setItemText(6, _translate("MainWindow", "Tokyo-Hot"))
        self.label.setText(_translate("MainWindow", "输入番号"))
        self.Search.setText(_translate("MainWindow", "搜索"))
        self.label_9.setText(_translate("MainWindow", "下载路径"))
        self.label_11.setText(_translate("MainWindow", "文件名"))
        self.downloadButton.setText(_translate("MainWindow", "下载"))
        self.statu.setAccessibleName(_translate("MainWindow", "0"))
        self.statu.setText(_translate("MainWindow", "获取状态"))
        self.label_5.setText(_translate("MainWindow", "片长"))
        self.label_4.setText(_translate("MainWindow", "发行日"))
        self.label_6.setText(_translate("MainWindow", "标签"))
        self.label_2.setText(_translate("MainWindow", "片名"))
        self.label_3.setText(_translate("MainWindow", "演员"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search), _translate("MainWindow", "搜索"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.download), _translate("MainWindow", "下载"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

